---
dependencies:
  auto_route: ^7.7.0
  auto_route_generator: ^7.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  form_builder_validators: ^9.0.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  go_router: ^9.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  riverpod: ^2.3.6
description: A new Flutter project.
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.0.5 <4.0.0'
flutter:
  uses-material-design: true
flutter_native_splash:
  color: '#FFFFFF'
  image: assets/icon_flutter.png
name: init_test_task
publish_to: none
version: 1.0.0+1